### ISSUE TITLE
Add linter

### ISSUE THREAD

**Issue by dzencot** [hexlet-components/react-app-example#1]

**Comment by Nesaq** [comment]
забрал

**Comment by dzencot** [comment]
Как успехи? Получается?

**Comment by ashikov** [comment]
@dzencot тут разве линтер должен быть не снаружи?

**Comment by dzencot** [comment]
Ну да. Это пример для 4 проекта, и ребята должны видеть пример настроек линтера.

**Comment by dzencot** [comment]
смержено https://github.com/hexlet-components/react-app-example/pull/4
